### ISSUE TITLE
Buen trabajo Luis

### ISSUE THREAD

**Issue by yosbel-penate** [luisalbalat/Proteus-8#1]
Podrias subir el proycto de proteus también, junto a las fotos, y mandarme un audio donde me des una pequeña explicacion del circuito que usaste y la pastilla, para entender por que usaste esa pastilla, sube el audio junto al proyecto, un audio para el semaforo y otro para el sumador, por escrito en el readmi es igual, como mejor te sea. Me cuadra el uso de las pastillas que hiciste.

**Comment by luisalbalat** [comment]
Ya realice las peticiones que me hizo. Y deje en el readme y audios el uso que le di a las pastillas.

**Comment by luisalbalat** [comment]
Y ya subi los biestables.
